#!/bin/env python
#------------------------------------------------------------------------#
# CommandBench - All-purpose command-line application benchmarking tool
# Copyright (C) 2009 Adam Wagner <awagner83@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------#

"""
Command-line application benchmarking software

usage:
    cb n command
    ex: repeat.py 10 ls -al
"""

from commandbench.process import Controller
import sys

try:
    # Parse command-line opts
    repetitions = int( sys.argv[1] )
    command = sys.argv[2:]

    # Create controller and execute
    Controller(command, repetitions).run()
    
except IndexError:
    print __doc__

