#!/bin/env python
#------------------------------------------------------------------------#
# CommandBench - All-purpose command-line application benchmarking tool
# Copyright (C) 2009 Adam Wagner <awagner83@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------#

"""
CLI interface to CommandBench
"""

if __name__ == '__main__':
    
    from commandbench.process import Controller
    from optparse import OptionParser
    
    # Parse command-line opts
    parser = OptionParser( 'Usage: %prog [options] COMMAND' )
    parser.add_option('-n', '--number', dest='repetitions', type="int",
            help='number of times to repeat COMMAND', default=1)
    options, command = parser.parse_args()

    if len( command ):
        # Create controller and execute
        Controller(command, options.repetitions).run()
    else:
        from commandbench.about import copyright_line
        print copyright_line, "\n"
        parser.print_help()

